const SooratYousaf56to111 = [
  {
    questionNo: 1,
    question: "برادران یوسف کہاں سے آ رہے تھے",
    options: ["   شام سے", "مصرسے", "لبنان سے", "الف اور ب دونوں"],
    correctAnswer: "شام سے",
  },
  {
    questionNo: 2,
    question: "سَنُرَاوِدُ کا مطلب ہے",
    options: ["طلب گندم ", "طلب کوشش", " طلب تحقیق"],
    correctAnswer: "طلب کوشش",
  },
  {
    questionNo: 3,
    question: "مصر میں کونسا نظام رائج تھا؟",
    options: ["راشننگ", "توریہه", "مال کے ساتھ", "منصفانہ"],
    correctAnswer: "راشننگ",
  },
  {
    questionNo: 4,
    question: "اولاد یعقوب نے کس بات کی خبر سنائی",
    options: ["موسم کی بندش", "غلہ کی بندش", "مال کی بندش", "سارے اپشن"],
    correctAnswer: "غلہ کی بندش",
  },
  {
    questionNo: 5,
    question: "توکل کا مطلب ہے",
    options: ["راھت", "بھروسہ", "ماوراء اراداہ الٰہی", "عہد و پیمان"],
    correctAnswer: "ماوراء اراداہ الٰہی",
  },
  {
    questionNo: 6,
    question: "خاندان یعقوب کا مصر میں داخل ہونا",
    options: [
      "فروانی نعمت کی علامت تھی",
      "نبوت کی علامت تھی",
      "فتح کی علامت تھی",
      "سارے اپشن",
    ],
    correctAnswer: "فتح کی علامت تھی",
  },
  {
    questionNo: 7,
    question: " ... تقدیر کس وقت موثر ہوتی ہے جب",
    options: ["ہم", "امید چاہے", "رسول چاہے", "اللہ چاہے"],
    correctAnswer: "اللہ چاہے",
  },
  {
    questionNo: 8,
    question: "لفظ  کید کے لغوی معنی ... ہیں",
    options: ["سب", "الزام سازی", "حیلہ سازی", "بہانے بازی    "],
    correctAnswer: "حیلہ سازی",
  },
  {
    questionNo: 9,
    question: "حکومت یوسف میں کونسا قانون نافذ تھا",
    options: ["سب", "مصری قانون", "شاہی قانون", "الہی قانون"],
    correctAnswer: "شاہی قانون",
  },
  {
    questionNo: 10,
    question: "حضرت یوسف کی پرورش کس نے کی",
    options: [
      "حضرت یعقوب نے",
      "انکی کنیز نے",
      "انکی پھوپھی نے",
      "انکی خالہ نے",
    ],
    correctAnswer: "انکی پھوپھی نے",
  },
  {
    questionNo: 11,
    question: "اخلاق انبیاء __ ہے",
    options: ["معاف کرنا", "چھوڑ دینا", "ظلم کرنا", "انتقام نہ لینا"],
    correctAnswer: "انتقام نہ لینا",
  },
  {
    questionNo: 12,
    question: "شریعت ابراہیم میں چور کی سزا",
    options: ["قتل کرنا", "کوڑے مارنا", "غلام بنانا", "قید کرنا"],
    correctAnswer: "غلام بنانا",
  },
  {
    questionNo: 13,
    question: "عزیز __ کو کہتے ہے",
    options: ["انسان کو", "مرد کو", "سرکار کو", "بادشاہ کو"],
    correctAnswer: "سرکار کو",
  },
  {
    questionNo: 14,
    question: "قمیض یوسف کتنی بار پیش کی گئی",
    options: ["2", "3", "4", "5"],
    correctAnswer: "3",
  },
  {
    questionNo: 15,
    question: "صبر کا آخری سرا___ ہے",
    options: ["امتحان", "خوشی", "کامیابی", "محنت"],
    correctAnswer: "کامیابی",
  },
  {
    questionNo: 16,
    question: "نفس کے سخت ترین غم کو کہتے ہے",
    options: ["سب", "المعنی", "بث النفس", "الشکا یہته"],
    correctAnswer: "بث النفس",
  },
  {
    questionNo: 17,
    question: "غلہ کی تقسیم کس کے زریعے ہوتی تھی",
    options: ["سب", "فی کس چھ شتر", "فی کس تین شتر", "فی کس ایک شتر"],
    correctAnswer: "فی کس ایک شتر",
  },
  {
    questionNo: 18,
    question: "خوشبوئے یوسف کو___ قرار دیا",
    options: ["امنع", "وحمی", "قدری", "خبطی"],
    correctAnswer: "خطبی",
  },
  {
    questionNo: 19,
    question: "اقتدار و تمکینت __ کا اجر ہے",
    options: ["سب", "جنتی", "دنیوی", "اخروی"],
    correctAnswer: "دنیوی",
  },
  {
    questionNo: 20,
    question: "اس زمانے میں غلہ کی قیمت ... تھی",
    options: ["سب", "مال کے بدلے مآل", "کرنسی", "نقدی"],
    correctAnswer: "مال کے بدلے مآل",
  },
  {
    questionNo: 21,
    question: ["اللہ کی نصرت کس وقت آتی ہے جب"],
    options: [
      "جنگ جیت جائے",
      "اسباب و علل سے مایوس ہو",
      "کفر پھیل جائے",
      "الف اور ب",
    ],
    correctAnswer: "اسباب و علل سے مایوس ہو",
  },
  {
    questionNo: 22,
    question: "دعوت علی بصیر کی بنیاد کیا ہے",
    options: ["حسد", "جھوٹ و فریب", "یقین و معرفت", "شرک و نفاق"],
    correctAnswer: "یقین و معرفت",
  },
  {
    questionNo: 23,
    question: "موحد کامل ہی کامل طور پر ---سے مبرا ہوتا ہے",
    options: ["سب سے", "بندگی", "شرک", "ایمان"],
    correctAnswer: "شرک",
  },
  {
    questionNo: 24,
    question: "رسول کی تسکین و قلب نصرت کیلیے --کی سنت جاریہ کا زکر ہوا ہے",
    options: ["سب کی", "علی کی", "اہل بیت کی", "اللہ کی"],
    correctAnswer: "اللہ کی",
  },
  {
    questionNo: 25,
    question: "شرک کے بارے میں رسولٌ نے کس کی مثال دی",
    options: ["اونٹ کی", "گھوڑے کی", "چیونٹی کی", "مکڑی کی"],
    correctAnswer: "_چیونٹی",
  },
  {
    questionNo: 26,
    question: "اس صورت میں کس نبی نے اپنی قوم سے مایوسی کا اظہار کیا",
    options: ["سب نے", "حضرت یعقوب", "حضرت نوح", "حضرت یوسف"],
    correctAnswer: "حضرت نوح",
  },
  {
    questionNo: 27,
    question: "صورت یوسف --- سورت ہے",
    options: ["مدنی", "مکی"],
    correctAnswer: "مکی",
  },
  {
    questionNo: 28,
    question: "اس صورت میں کل کتنی آیات ہیں",
    options: ["11", "112", "111", "110"],
    correctAnswer: "111",
  },
  {
    questionNo: 29,
    question: "ہر کامیابی کی صورت میں کیا کرنا چاہیے",
    options: ["تلاوت", "شکر", "نفرت", "صبر"],
    correctAnswer: "شکر",
  },
  {
    questionNo: 30,
    question: "تفسیر کے مطابق کونسی زندگی بہتر ہے",
    options: ["سب", "اسلامی", "شہری", "دیہی"],
    correctAnswer: "شہری",
  },
  {
    questionNo: 31,
    question: "گناہوں کی مغفرت کیلئے ---وسیلہ ہے",
    options: ["سب", "علماء", "اوصیاء", "انبیاء"],
    correctAnswer: "انبیاء",
  },
  {
    questionNo: 32,
    question: "ہر معاملے کو خدا سے مربوط کرنا کیا کہلاتا ہے",
    options: ["", "آداب بندگی", "آداب سرکشی", "الف اور ب دونوں"],
    correctAnswer: "آداب بندگی",
  },
  {
    questionNo: 33,
    question: "اولاد یعقوب نے اپنے والد سے کہا کہ ہم",
    options: ["معصوم ھیں", "بے گناہ ہے", "پاکیزہ ہے", "خطاکار ہیں "],
    correctAnswer: "خطاکار ہیں ",
  },
  {
    questionNo: 34,
    question:
      "امام جعفر صادق علیہ السلام کی روایات کے مطابق انکی دعا کو ----تک موخر کیا",
    options: [ "نمازِ شب تک", "شب جمعہ تک", "صبح تک","تمام آپشن"],
    correctAnswer: "شب جمعہ تک",
  },
  {
    questionNo: 35,
    question: "الفند ... کے معنی ہیں",
    options: ["الف اور ب", "دل کی کمزوری", "رائے کی کمزوری", "دماغ کی کمزوری"],
    correctAnswer: "رائے کی کمزوری",
  },
  {
    questionNo: 36,
    question: "کونسا تعلق مسا فتوں کو سمیٹ لیتا ہے",
    options: ["مادی", "قلبی", "جسمانی", "روحانی"],
    correctAnswer: "قلبی",
  },
  {
    questionNo: 37,
    question: "مصیبت کے وقت گریہ کرنا _ کی علامت ہے",
    options: ["تمام ", "رقت قلب کی", "شکر کی", "صبر کی"],
    correctAnswer: "رقت قلب کی",
  },
  {
    questionNo: 38,
    question: "کس چیز کے بغیر انبیاء کامیابی حاصل نہیں کر سکتے",
    options: ["الف اور ب", "ہمت", "صبر و تقویٰ", "ہدایت"],
    correctAnswer: "صبر و تقویٰ",
  },
  {
    questionNo: 39,
    question: "احسان وہ حربہ ہے کہ جسے",
    options: [
      "شرفاء استعمال کرتے ہیں",
      "مسکین استعمال کرتے ہیں",
      "غریب استعمال کرتے ہیں",
      "تمام آپشنز",
    ],
    correctAnswer: "شرفا استعمال کرتے ہیں",
  },
  {
    questionNo: 40,
    question: "آئمہ اہل بیت کے مطابق گناہ کبیرہ کتنے ہیں",
    options: ["9", "8", "7", "6"],
    correctAnswer: "7",
  },
];

export default SooratYousaf56to111;
