const SooratRahad = [
  {
    questionNo: "1",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "2",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "3",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "4",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "5",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "6",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "7",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "8",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "9",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "10",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "11",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "12",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "13",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "14",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "15",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "16",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "17",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "18",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "19",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "20",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "21",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "22",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "23",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "24",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "25",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "26",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "27",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "28",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "29",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "30",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "31",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "32",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "33",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "34",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "35",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "36",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "37",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "38",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "39",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
  {
    questionNo: "40",
    question: "",
    options: ["", "", "", ""],
    correctAnswer: "",
  },
];

export default SooratRahad;
